apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-discord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager-discord
  template:
    metadata:
      labels:
        app: alertmanager-discord
    spec:
      containers:
        - name: alertmanager-discord
          image: benjojo/alertmanager-discord
          env:
            - name: DISCORD_WEBHOOK
              value: "https://discord.com/api/webhooks/1471799568256729173/LgN645o7xkgrJwYh41QTzU64IapDLMSjE4iXq9pzDPWrqekI-OEMSqieEhqxF2_xLORf"
          ports:
            - containerPort: 9094
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-discord
spec:
  selector:
    app: alertmanager-discord
  ports:
    - port: 9094
      targetPort: 9094
